# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98e283fea9cd2a64eed140027ef77448679b801675e1b289684b62c42da514d031629353f28a201c26864f4448a99e1e191995d6ced7a485db8564857299a8c4

test:
  secret_key_base: 364a0f2089ed4872cedea0b3978f95b59817783375e17c852fababeeaa6662428063f43762055290055cbae1edb5f4b3b399bfab30669210d6590ba859e0eebd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
